import AppleCinnamon from './appleCinnamon.png'
import BambooBreeze from './bambooBreeze.png'
import BlackberryScone from './blackberryScone.png'
import ChampagneShimmer from './champagneShimmer.png'
import CranberryFields from './cranberryFields.png'
import FreshMountainAir from './freshmountainAir.png'
import LavenderDreams from './lavenderDreams.png'
import MorningCoffee from './morningCoffee.png'
import OrangeCitrus from './orangeCitrus.png'
import PumpkinSpicedLatte from './pumpkinSpicedLatte.png'
import StrawberryShortCake from './strawberryShortCake.png'
import RaspberryDelight from './raspberryDelight.png'
import VanillaSwirl from './vanillaSwirl.png'
import VelvetPeach from './velvetPeach.png'
import CategoryCandel from './CategoryCandels.png'
export { CategoryCandel, AppleCinnamon, BambooBreeze, BlackberryScone, ChampagneShimmer, CranberryFields, FreshMountainAir, LavenderDreams, MorningCoffee, OrangeCitrus, PumpkinSpicedLatte, RaspberryDelight, VanillaSwirl, VelvetPeach, StrawberryShortCake }