import HeroImg from './img/img-hero.jpg'
import FreshFlower from './img/flowers/freshFlower.png'
import Candel from './img/flowers/candel.png'
import DriedFlower from './img/flowers/driedFlower.png'
import LivePlant from './img/flowers/livePlant.png'
import Fresheners from './img/flowers/fresheners.png'
import FrontHouseLogo from './logo.jpg'
import ImgService from './img/image.png'
import WeddingPlace from './img/weddingPlace.jpg'
export { HeroImg, FreshFlower, Candel, DriedFlower, LivePlant, Fresheners, FrontHouseLogo, ImgService, WeddingPlace }